receivers:
  # use the efficient otlp grpc protocol
  otlp:
    protocols:
      grpc:
        
exporters:
  # metrics exporter
  prometheus:
    # prometheus will scrape from here
    endpoint: :8889
    resource_to_telemetry_conversion:
      enabled: true

  # traces exporter
  otlp:
    endpoint: jaegar:4317
    tls:
      insecure: true

processors:
  # enable batching by adding it to processors in the pipeline
  # this is important for performance, but disabled for demo purposes
  # https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/batchprocessor/README.md
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp]